name: NextJs 14 CI/CD
run-name: ${{ github.actor }} is testing
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Configure profile
        run:  aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY }}" --profile test-sync-env && aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_KEY }}" --profile test-sync-env && aws configure set region "ap-southeast-1" --profile test-sync-env
      - name: Generate .env 
        run: npm run sync-env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t huylejh/next-cicd .
      - name: Publish image to docker hub
        run: docker push huylejh/next-cicd:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Delete old container
        run: docker rm -f next-cicd-container
      - name: Delete old image
        run: docker image rm image huylejh/next-cicd:latest
      - name: Pull image from docker hub
        run: docker pull huylejh/next-cicd:latest
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name next-cicd-container huylejh/next-cicd